export const FETCH_PRODUCTS = "GET_PRODUCTS";
export const FAIL_RPODUCTS = "FAIL_RPODUCTS";
export const SUCCESS_RPODUCTS = "SUCCESS_RPODUCTS";
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const SUB_QUANTITY = "SUB_QUANTITY"
export const ADD_QUANTITY = "ADD_QUANTITY"